fondo_sct/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import TempView

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^miembros/', include('miembros.urls', namespace='miembros')), 
	url(r'^$', TempView.as_view(), name='dashboard')
]

miembros/urls.py
from django.conf.urls import url
from . import views 

urlpatterns = [

	url(r'^$', 
		views.MiembrosListView.as_view(), 
		name='list'), 
	
	url(r'^nuevo/$', 
		views.MiembrosCreateView.as_view(), 
		name='add'), 

	url(r'^(?P<pk>\d+)/edit/$', 
		views.MiembrosUpdateView.as_view(), 
		name='edit'), 
	

	url(r'^carga/$', 
		views.CargaUsuarios.as_view(), 
		name='carga'), 

	]

"""
	url(r'^carga/$', 
		views.CargaUsuarios.as_view(), 
		name='carga'), 
	
"""

core/models.py
from django.db import models

# Create your models here.

miembros/models.py
from django.db import models
from django.conf import settings

# ==================================================
# Model Managers
# ==================================================

class MiembroManager(models.Manager):

	def activos(self):
		qs = self.filter(activo=True)
		return qs


# ==================================================
# Model Classes
# ==================================================

class Banco(models.Model):
	nombre	= models.CharField(max_length=50)

	def __str__(self):
		return self.nombre

	class Meta:
		ordering=['nombre']


class Miembro(models.Model):
	nombre		= models.CharField(max_length=100)
	email		= models.EmailField()
	cuenta		= models.CharField(max_length=50, blank=True)
	banco		= models.ForeignKey(Banco, null=True, on_delete=models.SET_NULL)
	fecha_nac	= models.DateField(null=True)
	fecha_ing	= models.DateField(null=True)
	activo		= models.BooleanField(default=True)

	objects = MiembroManager()
	
	def __str__(self):
		return self.nombre

	def save(self, *args, **kwargs):
		self.nombre = self.nombre.strip().title()
		self.email = self.email.strip().lower()
		super(Miembro, self).save(*args, **kwargs)

	class Meta:
		ordering=['nombre']
		

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from miembros.models import Miembro 

# ==================================================
# ==================================================

class CunaUser(AbstractUser):

	miembro = models.ForeignKey(Miembro, null=True, 
				on_delete=models.SET_NULL,
				related_name='user')

	def __str__(self):
		r = self.username
		if self.miembro:
			r = self.miembro.nombre
		return r

miembros/forms.py
from django import forms
from bootstrap_datepicker_plus import DatePickerInput

from .models import Miembro

class MiembroForm(forms.ModelForm):

	#'''
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		self.fields['fecha_nac'].widget = DatePickerInput(format='%Y-%m-%d')
		self.fields['fecha_nac'].required = False

		self.fields['fecha_ing'].widget = DatePickerInput(format='%Y-%m-%d')
		self.fields['fecha_ing'].required = False

		self.fields['cuenta'].required = False
		self.fields['banco'].required = False
	#'''

	class Meta:
		model = Miembro

		fields = [ 'nombre', 'email',  'fecha_nac', 
			'fecha_ing', 'cuenta', 'banco' ]

	'''
	nombre	
	email	
	cuenta	
	banco	
	fecha_nac
	fecha_ing
	activo	
	#'''

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CunaUser 

# ============================================================
# ============================================================

class CunaUserCreationForm(UserCreationForm):

	class Meta(UserCreationForm.Meta):
		model = CunaUser
		fields = ( 'username', 'email', 'miembro' )


class CunaUserChangeForm(UserChangeForm):

	class Meta:
		model = CunaUser
		fields = ( 'username', 'email', 'miembro' )

fondo_sct/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView

class TempView(TemplateView):
	template_name = 'temp.html'

class MainRedirectView(RedirectView):
	def get_redirect_url(self, *args, **kwargs):
		return '#'
		# return reverse_lazy('namespace:view_name', kwargs='...')

miembros/views.py
from django.shortcuts import render, redirect
from django.views.generic import View 
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.urlresolvers import reverse_lazy

from .models import Miembro
from .forms import MiembroForm
from core.utils import load_miembros

# ==================================================
# Mixins
# ==================================================

class MiembroMixin(LoginRequiredMixin):
	model = Miembro
	success_url = reverse_lazy('miembros:list')


class MiembroEditMixin(MiembroMixin, PermissionRequiredMixin):
	template_name = 'miembros/edit.html'
	form_class = MiembroForm
	permission_required = ('miembros.can_add', 'miembros.can_edit')


# ==================================================
# Clientes Views
# ==================================================

class MiembrosListView(MiembroMixin, ListView):
	template_name = 'miembros/list.html'

	def get_queryset(self):
		qs = Miembro.objects.activos()
		return qs


class MiembrosCreateView(MiembroEditMixin, CreateView):
	pass


class MiembrosUpdateView(MiembroEditMixin, UpdateView):
	pass


#"""
# Sólo se utiliza una vez
class CargaUsuarios(View):

	def get(self, request, *args, **kwargs):
		print()
		print('*'*50)
		print('Executing load users ...')
		print('*'*50)
		print()

		load_miembros()
		return redirect('miembros:list')
#"""

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base (bootstrap3).html
{% load static %}

<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>
		{% block title %}Fondo SCT{% endblock %}
	</title>

	<!-- jquery 1.12.1 -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/cupertino/jquery-ui.css"
		 type="text/css">
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" 
		type="text/javascript"></script>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
		integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" 
		crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
		integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
		crossorigin="anonymous"></script>
	
	<!-- block for app specific css -->
	<link rel="stylesheet" href="{% static 'css/main.css' %}" >
	{% block app_css %}

	{% endblock %}

</head>
<body>

	<div class="container-fluid">

		<div id="header" class="row">
			<div class="col-sm-12 col-md-12 col-lg-12">
				<nav class="navbar navbar-inverse navbar-fixed-top">
				  <div class="container-fluid">
					<div class="navbar-header">
					  <a class="navbar-brand" href="#">Fondo SCT</a>
					</div>

	<ul id="main_menu" class="nav navbar-nav">
		<li>
			<a href="{% url 'miembros:list' %}">Equipo</a>
		</li>
	</ul>

	<ul class="nav navbar-nav navbar-right">
		{% if request.user.is_authenticated %}
			<!-- Cómo cambiar este enlace? -->
			<li><a href="#">Hola {{ user.first_name }}!</a></li>
			{% if user.is_staff %}
				<li><a href="/admin/">Administración</a></li>
			{% endif %}
			<li><a href="{% url 'logout' %}">Cerrar Sessión</a></li>
		{% else %}
			<li><a href="{% url 'login' %}">Iniciar Sessión</a></li>
		{% endif %}
	</ul>

				  </div>
				</nav>
			</div>
		</div>
	
		<div id="application" class="row">
			<div id="content" class="col-sm-12 col-md-12 col-lg-12">
				{% block content %}
				{% endblock %}
			</div>
		</div>

	</div>

	<script>

		$(document).ready(function() {
			{% block domready %}
			{% endblock %}            
		});

		$(function() {

			{% block javascript %}
			{% endblock javascript %}

		})

	</script>

</body>
</html>

templates/base (bootstrap4).html
{% load static %}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>
		{% block title %}Fondo SCT{% endblock %}
	</title>
	
	<!-- block for app specific css -->
	<link rel="stylesheet" href="{% static 'css/main.css' %}" >
	{% block app_css %}

	{% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Fondo SCT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div id="application" class="row">
	<div id="content" class="col-sm-12 col-md-12 col-lg-12">
		{% block content %}
		{% endblock %}
	</div>
</div>

<script>

$(document).ready(function() {
	{% block domready %}
	{% endblock %}            
});

$(function() {
	{% block javascript %}
	{% endblock javascript %}
})

</script>

</body>
</html>

templates/base.html
{% load static %}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

{% block extrahead %}       {# Extra Resources Start #}
{{ form.media }}            {# Form required JS and CSS #}
{% endblock %}              {# Extra Resources End #}

<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>
		{% block title %}Fondo SCT{% endblock %}
	</title>
	
	<!-- fontawsome for bootstrap -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" 
		integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" 
		crossorigin="anonymous">

	<!-- block for app specific css -->
	<link rel="stylesheet" href="{% static 'css/main.css' %}" >
	{% block app_css %}

	{% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <a class="navbar-brand" href="#">Fondo SCT</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	<ul class="navbar-nav mr-auto">
	  <li class="nav-item active">
			<a href="{% url 'miembros:list' %}">Equipo</a>
	  </li>
	</ul>
	<div class="navbar">
		{% if request.user.is_authenticated %}

			<span class="navbar-text">
				Hola 
				{% if user.miembro %}
					{{ user.miembro.nombre }}
				{% else %}
					{{ user.username }}
				{% endif %}!
			</span>

			{% if user.is_staff %}
			    <a class="nav-link" href="/admin/">
			    	<i class="fas fa-lock" title="Administración"></i>
			    </a>
			{% endif %}

			<a class="nav-link" href="{% url 'logout' %}">
				<i class="fas fa-sign-out-alt" title="Cerrar Sessión"></i>
			</a>

		{% else %}
			<a class="nav-link" href="{% url 'login' %}">
				<i class="fas fa-sign-in-alt" title="Iniciar Sessión"></i>
			</a>
		{% endif %}

	</div>
  </div>
</nav>

<div id="application">
	<div id="content" class="container-fluid">
		{% block content %}
		{% endblock %}
	</div>
</div>

<script>

$(document).ready(function() {
	{% block domready %}
	{% endblock %}            
});

$(function() {
	{% block javascript %}
	{% endblock javascript %}
})

</script>

</body>
</html>

templates/miembros/edit.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

{% block extrahead %}       {# Extra Resources Start #}
{{ form.media }}            {# Form required JS and CSS #}
{% endblock %}              {# Extra Resources End #}


{% block title %}
	{% if object %}
		Actualizar Datos
	{% else %}
		Registrar Miembro del Equipo
	{% endif %}
{% endblock %}

{% block content %}

	<div class="row"><div class="col-sm-12">
		<h1>
			{% if object %}
				Actualizar Datos
			{% else %}
				Registrar Miembro del Equipo
			{% endif %}
		</h1>
	</div></div>

	<div class="row">
		<div class="col-sm-6">
			<form action="" method="post" class="form">
				{% csrf_token %}
				{% bootstrap_form form %}
				{% buttons %}
					<button type="submit" class="btn btn-primary">
						<i class="fas fa-save fa-fw"></i>
							{% if object %}
								Grabar Cambios
							{% else %}
								Agregar Miembro
							{% endif %}
					</button>
				{% endbuttons %}
			</form>
		</div>
	</div>

{% endblock %}

{% block domready %}

$("#id_nombre").focus();

{% endblock %}

templates/miembros/list.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
Miembros Reistrados
{% endblock %}

{% block app_css %}
{% endblock app_css %}

{% block content %}

	<div id="app_header">
		<h1>Miembros del Equipo</h1>
	</div>

	<a href="{% url 'miembros:add' %}" class="button btn btn-outline-primary btn-sm">
		<i class="fas fa-user-plus fa-fw"></i>
		Nuevo Miembro
	</a>

	<!--
	<a href="{% url 'miembros:carga' %}" class="button btn btn-outline-primary btn-sm">
		<i class="fas fa-user-plus fa-fw"></i>
		Carga Inicial
	</a>
	-->

	<table class="table table-sm table-striped table-hover table-bordered">
		<thead class="thead-light">
			<tr>
				<th>Nombre</th>
				<th>Email</th>
				<th>Fecha Nac.</th>
				<th>Cuenta</th>
				<th>Banco</th>
				<th>Fecha Ing.</th>
				<th>Usuario</th>
			</tr>
		</thead>
		<tbody>
			{% for item in object_list %}
					<td>
						<a href="{% url 'miembros:edit' item.id %}">
							{{ item.nombre }}
						</a>
					</td>
					<td>{{ item.email }}</td>

					<td>
						{% if item.fecha_nac %}
							{{ item.fecha_nac }}
						{% endif %}
					</td>

					<td>{{ item.cuenta }}</td>
					<td>{{ item.banco.nombre }}</td>

					<td>
						{% if item.fecha_ing %}
							{{ item.fecha_ing }}
						{% endif %}
					</td>

					<td>{{ item.user.username }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

{% endblock %}

{% block domready %}

{% endblock %}

{% block javascript %}
{% endblock javascript %}

templates/temp.html
{% extends "base.html" %} 
{% block content %} 

<h1>This WebSite is Under Construction</h1>

{% endblock %}